# **Inversiones en startups**
Este notebook contiene información sobre inversiones en startups en EEUU y España. 

También analiza información sobre inversiones en startups de Europa e Israel vs EEUU que tengan que ver, o no tengan que ver, con startups de inteligencia artifical generativa. 

---
---
---

>

# **1. Inversiones en startups de EEUU y España**
Este notebook contiene información sobre inversiones en startups en EEUU y España. 


Fuente informativa 1 = https://www.statista.com/statistics/277501/venture-capital-amount-invested-in-the-united-states-since-1995/#:~:text=In%202022%2C%20the%20value%20of,nearly%20241%20billion%20U.S.%20dollars.

Fuente informativa 2 = https://elreferente.es/actualidad/inversiones-startups-espana-2022/#:~:text=El%20sector%20SaaS%20cuenta%20en,arroja%20informaci%C3%B3n%20sobre%20diferentes%20asuntos.

---

In [3]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

import warnings

# Suprime todas las advertencias
warnings.filterwarnings("ignore")

In [4]:
investment_us_startup_2022    = 240900000000
investment_spain_startup_2022 =   3365000000

prcntg_investment_spain_startup_2022 = round(((investment_spain_startup_2022 * 100) / investment_us_startup_2022), 2)

print(f"Importe de inversión en startups estadounidenses en 2022: {investment_us_startup_2022}$ = 235 Billones de Dolares")
print(f"Importe de inversión en startups españolas en 2022: {investment_spain_startup_2022}$ = 3,365 Billones de Dolares\n")

print(f"El dinero invertido en las startups españolas supone el {prcntg_investment_spain_startup_2022}% de lo invertido en las de Estados Unidos.")

Importe de inversión en startups estadounidenses en 2022: 240900000000$ = 235 Billones de Dolares
Importe de inversión en startups españolas en 2022: 3365000000$ = 3,365 Billones de Dolares

El dinero invertido en las startups españolas supone el 1.4% de lo invertido en las de Estados Unidos.


Vamos a crear un data frame manualmente

In [5]:
inves_comp = {
    'Country': ['Estados Unidos','España'],
    'Investment ($B)': [240.9, 3.365]
}

df_inves_comp = pd.DataFrame(inves_comp)
df_inves_comp

Country  Investment ($B)
0  Estados Unidos          240.900
1          España            3.365

In [6]:
# Creamos un gráfico de barras con Plotly
fig = px.bar(df_inves_comp, x='Country', y='Investment ($B)', text='Investment ($B)',
             labels={'Country': 'País', 'Count': 'Número de Startups'},
             title='Billones de Dolares Invertidos en Startups de Estados Unidos vs. España en el año 2022',
             color_discrete_sequence=px.colors.qualitative.Plotly)

# Centramos el texto del título de la gráfica
fig.update_layout(title_x=0.5)

# Mostramos el gráfico
fig.show()

Billones de dolares invertidos en startups en el 2022:

- Estados Unidos, $240.9B = 240.900.000.000 millones de dolares

- España, $3,365 = 3.365.000.000 millones de dolares

Como podemos ver, la diferencia es abismal.

In [6]:
# Imprimimos el gráfico de tarta
fig = go.Figure(data=[go.Pie(labels=df_inves_comp['Country'].tolist(), values=df_inves_comp['Investment ($B)'].tolist())]) 

# Centramos el texto del título de la gráfica
fig.update_layout(title_text='Percentage de Inversíon en Startups de Estados Unidos vs. España en el año 2022', title_x=0.5)

# Mostramos el gráfico
fig.show()

Los 3,365 billones de dolares invertidos en las startups españolas, suponen el 1,38% de los 240,9 billones de dolares invertidos en las startups estadounidenses.

---
### Conclusión: 
# Estados Unidos, la tierra de las startups con oceanos de invesiones   
1. La diferencia de capital invertido en startups de Estados Unidos y en españolas en el 2022 es apabullante. En España, solo se invierte el 1,4% del total invertido en startups en Estados Unidos. En concreto, el año 2022 las startups estadounidenses tuvieron una financiación en inversiones de 240.9 billones de dolares frente a los 3,665 billones de dolares invertidos en España. Sin palabras.


>

---
---
---

>

# **2. Inversiones en startups de Europa e Israel frente a las de Estados Unidos**
Análisis de inversiones en startups de Europa e Israel vs EEUU en relación, o no, con startups de inteligencia artifical generativa.

---
Fuente informativa 3 = https://assets.website-files.com/5f217a8e6bc2c8058e803083/652da0d05b332864d89b8445_17%20October%20-%20Accel%202023%20Euroscape.pdf

---

#### Preparamos los datos extraidos del análisis del "Informe Euroscape de Accel 2023" a modo de diccionarios para despues convertirlos en data frames

In [7]:
# Europa e Israel - Las mayores rondas de financiamiento privado no relacionadas con IA generativa en el último año
non_gen_ai_eu_isr = {
    'Company': ['Wiz', 'Builder AI', 'Cato Networks', 'Dataiku', 'Snyk'],
    'Private Rounds ($M)': [300, 250, 238, 200, 197]
}

# Estados Unidos - Las mayores rondas de financiamiento privado no relacionadas con IA generativa en el último año
non_gen_ai_us = {
    'Company': ['Databricks', 'Rippling', 'Drata', 'Komodo Health', 'Blackpoint'],
    'Private Rounds ($M)': [500, 500, 200, 200, 190]
}

# Europa e Israel - Las mayores rondas de financiamiento privado relacionadas con IA generativa en el último año
gen_ai_eu_isr = {
    'Company': ['Hugging Face', 'AI21 labs', 'Poolside', 'Mistral AI', 'Aleph Alpha', 'Stability AI', 'Synthesia'],
    'Private Rounds ($M)': [235, 155, 126, 113, 109, 101, 90]
}

# Estados Unidos - Las mayores rondas de financiamiento privado relacionadas con IA generativa en el último año
gen_ai_us = {
    'Company': ['OpenAI', 'Inflection', 'Anthropic (sep 23)', 'Anthropic (May 23)', 'CoreWeave', "Adept", 'Anthropic (Feb 23)'],
    'Private Rounds ($M)': [10000, 1300, 1250, 450, 421, 350, 300]
}


#### Creamos los data frames

In [8]:
# Rondas de financicion UE vs EEUU en startups  
df_non_gen_ai_eu_isr = pd.DataFrame(non_gen_ai_eu_isr)
df_non_gen_ai_us = pd.DataFrame(non_gen_ai_us)

# Rondas de financicion UE vs EEUU en startups de IA genenerativa 
df_gen_ai_eu_isr = pd.DataFrame(gen_ai_eu_isr)
df_gen_ai_us = pd.DataFrame(gen_ai_us)

In [9]:
# Creamos un gráfico de barras con Plotly
fig = px.bar(df_non_gen_ai_eu_isr, x='Company', y='Private Rounds ($M)', text='Private Rounds ($M)',
             labels={'Company': 'Startups', 'Private Rounds ($M)': 'Rondas Privadas ($M)'},
             title='Europa e Israel - Las mayores rondas de financiamiento privado no relacionadas con IA generativa en el último año',
             color_discrete_sequence=px.colors.qualitative.Plotly)

# Centramos el texto del título de la gráfica
fig.update_layout(title_x=0.5)

# Mostramos el gráfico
fig.show()

In [10]:
# Creamos un gráfico de barras con Plotly
fig = px.bar(df_non_gen_ai_us, x='Company', y='Private Rounds ($M)', text='Private Rounds ($M)',
             labels={'Company': 'Startups', 'Private Rounds ($M)': 'Rondas Privadas ($M)'},
             title='Estados Unidos - Las mayores rondas de financiamiento privado no relacionadas con IA generativa en el último año',
             color_discrete_sequence=px.colors.qualitative.Plotly)

# Centramos el texto del título de la gráfica
fig.update_layout(title_x=0.5)

# Mostramos el gráfico
fig.show()

In [11]:
# Creamos un gráfico de barras con Plotly
fig = px.bar(df_gen_ai_eu_isr, x='Company', y='Private Rounds ($M)', text='Private Rounds ($M)',
             labels={'Company': 'Startups', 'Private Rounds ($M)': 'Rondas Privadas ($M)'},
             title='Europa e Israel - Las mayores rondas de financiamiento privado relacionadas con IA generativa en el último año',
             color_discrete_sequence=px.colors.qualitative.Plotly)

# Centramos el texto del título de la gráfica
fig.update_layout(title_x=0.5)

# Mostramos el gráfico
fig.show()

In [12]:
# Creamos un gráfico de barras con Plotly
fig = px.bar(df_gen_ai_us, x='Company', y='Private Rounds ($M)', text='Private Rounds ($M)',
             labels={'Company': 'Startups', 'Private Rounds ($M)': 'Rondas Privadas ($M)'},
             title='Estados Unidos - Las mayores rondas de financiamiento privado relacionadas con IA generativa en el último año',
             color_discrete_sequence=px.colors.qualitative.Plotly)

# Centramos el texto del título de la gráfica
fig.update_layout(title_x=0.5)

# Mostramos el gráfico
fig.show()

In [13]:
# Combinar los DataFrames usando pd.concat
df_gen_ai_comb = pd.concat([df_gen_ai_eu_isr, df_gen_ai_us])

df_gen_ai_comb_ordn = df_gen_ai_comb.sort_values(by='Private Rounds ($M)', ascending=False)

# Crear un gráfico de barras con Plotly para mostrar ambos conjuntos de datos
fig = px.bar(df_gen_ai_comb_ordn, x='Company', y='Private Rounds ($M)', text='Private Rounds ($M)',
             color='Company',
             labels={'Company': 'Startup', 'Private Rounds ($M)': 'Rondas Privadas ($M)'},
             title='Las mayores rondas de financiamiento privado relacionadas con IA generativa en el último año')

# Centrarmos el texto del título de la gráfica
fig.update_layout(title_x=0.5)

# Mostramos el gráfico
fig.show()

In [14]:
# Creamos un gráfico donut con Plotly
fig = px.pie(df_gen_ai_comb, names='Company', values='Private Rounds ($M)',
             title='Porcentaje de rondas de financiamiento privado ($M)',
             labels={'Company': 'Compañia', 'Private Rounds ($M)': 'Rondas de financiamiento privado ($M)'})

# Mostramos el gráfico
fig.update_traces(hole=0.4)  # Añadimos un agujero para convertirlo en un gráfico donut

# Centrarmos el texto del título de la gráfica
fig.update_layout(title_x=0.5)

# Mostramos el gráfico
fig.show()

---
### Conclusión 1: 
# **La inversión en IA generativa en EEUU se dispara**
1. En cuanto a las mayores rondas de finciamiento privado en el año 2023 en Europa e Israel vs. Estados Unidos en startups no relacionads con inteligencia artificial (IA) generativa, observamos que la diferencia no es tan grande. Respecto a la inversión en startups de ***Europa e Israel se ha conseguido hasta el 74,5% de lo que se ha invertido en startups estadounidenses***.

2. La cosa cambia radicalmente en el panorama de las startups de la IA generativa. En el último año, ***en startups de inteligencia artificial generativa de Estados Unidos, se ha invertido un 94,4% más que Europa e Israel juntos***. 

### Conclusión 2: 
# **OpenAI is eating AI**
1. Es bestial la diferencia entre la mayor ronda de financimiento privado vista en 2023, protagonizada por OpenAI (10.000 Millones de Dolares) y la segunda startup Inflection (1.300 Millones). Es casi 10x. Es cierto que si sumamos todo lo que ha levantado Anthropic en este 2023, nos da la cifra de 2.000 millones de dolares, pero aún y todo, OpenAI ha conseguido 8x más que su competidor. El futuro de la IA generativa pasa por estos dos ultimos actores, pero lo que queda claro es que ***OpenAI se está comiendo la IA generativa***.